version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "google.golang.org/grpc"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
