name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15.5'
      - uses: actions/cache@v2
        with:
          path: /home/runner/go/mod
          key: go-mod-cache-${{ hashFiles('go.sum') }}
          restore-keys: |
            go-mod-cache-
      - run: go mod verify
      - run: make tools pebble-start-install test

