name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15.5'
      - name: Cache (Go Modules)
        uses: actions/cache@v2
        env:
          cache-name: go-mod-cache
        with:
          path: /home/runner/go/pkg/mod
          key: ${{ env.cache-name}}-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ env.cache-name}}-
      - name: Cache (Go Build)
        uses: actions/cache@v2
        env:
          cache-name: go-build-cache
          cache-dir: /home/runner/.cache/go-build
        with:
          path: 
          key: ${{ env.cache-name}}-${{ hashFiles(format('{0}/**/*', env.cache-dir)) }}
          restore-keys: |
            ${{ env.cache-name}}-
      - run: go mod verify
      - run: make tools pebble-start-install test

