name: test
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'
  pull_request:
    branches:
      - '**'
jobs:
  go-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15.8'
      - name: Cache (Go Modules)
        uses: actions/cache@v2.1.4
        env:
          cache-name: go-mod-cache
        with:
          path: /home/runner/go/pkg/mod
          key: ${{ env.cache-name}}-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ env.cache-name}}-
      - name: Cache (Go Build)
        uses: actions/cache@v2.1.4
        env:
          cache-name: go-build-cache
          cache-dir: /home/runner/.cache/go-build
        with:
          path: ${{ env.cache-dir }}
          key: ${{ env.cache-name}}-${{ hashFiles(format('{0}/**/*', env.cache-dir)) }}
          restore-keys: |
            ${{ env.cache-name}}-
      - name: Cache (Pebble)
        uses: actions/cache@v2.1.4
        env:
          cache-name: pebble-cache
          cache-dir: /home/runner/go/src/github.com/letsencrypt/pebble
        with:
          path: ${{ env.cache-dir }}
          key: ${{ env.cache-name}}-${{ hashFiles(format('{0}/**/*', env.cache-dir)) }}
          restore-keys: |
            ${{ env.cache-name}}-
      - name: Verify Modules
        run: go mod verify
      - name: Run Tests
        run: make tools pebble-start test
  documentation-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate Markdown Links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          folder-path: 'docs'

